#!/usr/bin/env bash
# script to install nginx

sudo apt-get update
sudo apt-get install nginx -y

echo "server {
   listen 80;
   server_name localhost;
   root /var/www/html;
   index index.html;
   location / {
       return 200 'Hello World!';
   }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo systemctl restart nginx
echo "Hello World!"

