#!/usr/bin/env bash
# Use a custom header to configure nginx server for multiple servers
apt-get -y update
apt-get -y install nginx

sudo chown -R "$USER:$USER" /etc/nginx

server_name=$(hostname)

sudo sed -i "/http {/a \        add_header X-Served-By \"$server_name\";" /etc/nginx/nginx.conf

sudo service nginx restart

