#!/usr/bin/env bash
#A bash script that adds a custom Nginx response header

#Update Nginx
apt-get -y update

#install Nginx if not installed 
apt-get -y install nginx

sudo chown -R "$USER:$USER" /etc/nginx


server_name=$(hostname)


sudo sed -i "/http {/a \        add_header X-Served-By \"$server_name\";" /etc/nginx/nginx.conf


sudo service nginx restart
