#!/usr/bin/env bash

#A Bash script that generates a MySQL dump and creates a compressed archive out of it.

format=$(date +"%d-%m-%y")
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$format".tar.gz backup.sql
