#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
file_h="Best School"

if [ -e "$file_h" ]
then

    echo "Best School file exists"
    if [ -s "$file_h" ]
    then
        echo "Best School file is not empty"
    else
        echo "Best School file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "Best School is a regular file"
    fi
else
    echo "Best School file does not exist"
fi
